# DIV2K with random kernels. Used for super-resolution experiment

defaults:
 - degradation: gaussian_blur
 - noise: gaussian

name: patch
x_flip: True
patch_size: 128
# increase actual patch-size to counteract cropping
# should be equal to the size of the blur kernel used as corruption
inflate_patches: 0
num_patches_per_image: 128  # this is the speed-up factor over loading each image individually
patch_cache_size: 8192
space_conditioning: True
full_test: True
cuda: True
need_clean: True
need_noisy: True

train_path: ${paths.data}/div2k/div2k_train_full.zip
test_path: ${paths.data}/div2k/div2k_val_full.zip
